# Generated by Django 2.0.7 on 2020-05-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program_skills',
            new_name='Program_skill',
        ),
    ]
