# Generated by Django 2.0.7 on 2020-05-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Programming_skill',
        ),
    ]
