# Generated by Django 2.1.7 on 2020-06-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20200516_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('git_url', models.CharField(max_length=250, verbose_name='Git Url')),
                ('hosted_url', models.CharField(max_length=250, verbose_name='Hosted Url')),
                ('date', models.DateField()),
            ],
        ),
    ]
