# Generated by Django 2.1.7 on 2020-07-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_experience_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='date',
        ),
    ]
